<a href="https://colab.research.google.com/github/Keerthi87140/ICP-WEEK2/blob/main/ICP_WEEK_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
class Employee:
    # Class variable to count the number of employees
    employee_count = 0

    def __init__(self, name, family, salary, department):
        self.name = name
        self.family = family
        self.salary = salary
        self.department = department
        Employee.employee_count += 1

    def average_salary(self, employees):
        total_salary = sum(employee.salary for employee in employees)
        return total_salary / len(employees) if employees else 0

    def __str__(self):
        return f"Employee(name={self.name}, family={self.family}, salary={self.salary}, department={self.department})"

class FulltimeEmployee(Employee):
    def __init__(self, name, family, salary, department):
        super().__init__(name, family, salary, department)
        # attributes  to FulltimeEmployee can be added here

    def __str__(self):
        return f"FulltimeEmployee(name={self.name}, family={self.family}, salary={self.salary}, department={self.department})"

# Creating instances of Employee
emp1 = Employee("Keerthi", "Yadlapati", 90000, "IT")
emp2 = Employee("Akshitha", "Bhavanam", 80000, "HR")

# Creating instances of FulltimeEmployee
ft_emp1 = FulltimeEmployee("Deepthi", "Alluri", 85000, "Marketing")
ft_emp2 = FulltimeEmployee("Sathvika", "Kesamaneni", 70000, "Finance")

# List of all employees
all_employees = [emp1, emp2, ft_emp1, ft_emp2]

# Calculate and print average salary(average of salary of all employees)
employee = Employee("Temp", "Temp", 0, "None")
print(f"Average Salary: {employee.average_salary(all_employees)}")

# Print the details of each employee
for emp in all_employees:
    print(emp)

# Print total number of employees
print(f"Total number of employees: {Employee.employee_count}")


Average Salary: 81250.0
Employee(name=Keerthi, family=Yadlapati, salary=90000, department=IT)
Employee(name=Akshitha, family=Bhavanam, salary=80000, department=HR)
FulltimeEmployee(name=Deepthi, family=Alluri, salary=85000, department=Marketing)
FulltimeEmployee(name=Sathvika, family=Kesamaneni, salary=70000, department=Finance)
Total number of employees: 5


In [5]:
import numpy as np

#random vector of size 20 with floats in the range 1-20
vector = np.random.uniform(1, 20, size=20)
print(vector)
print()

#vector to 4x5
matrix = vector.reshape(4, 5)

#Replace the max in each row with 0 (axis=1)
# Get the indices of the maximum values along axis=1
max_indices = np.argmax(matrix, axis=1)

# Create a boolean mask where the max values are True
mask = np.arange(matrix.shape[1]) == max_indices[:, None]

# Apply the mask to set max values to 0
matrix[mask] = 0

# Output the result
print("Matrix after replacing max values with 0:")
print(matrix)

[10.60489783 18.50593155 10.81832637 12.70748452 12.41578758 12.07718122
 13.16560585 17.56043397 18.78338925  1.99975503 19.71365595 15.12651912
 10.86707038 17.56930849 18.66623914  2.72782396  5.17222583 19.29108754
  7.76918748 18.00640469]

Matrix after replacing max values with 0:
[[10.60489783  0.         10.81832637 12.70748452 12.41578758]
 [12.07718122 13.16560585 17.56043397  0.          1.99975503]
 [ 0.         15.12651912 10.86707038 17.56930849 18.66623914]
 [ 2.72782396  5.17222583  0.          7.76918748 18.00640469]]
